# DAT210x - Programming with Python for DS

## Module6- Lab3

This code is intentionally missing! Read the directions on the course lab page!

In [34]:
import pandas as pd
import numpy as np


In [2]:
# .. your code here ..
X = pd.read_csv('Datasets/parkinsons.data', index_col=0)
X

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
name                                                                      
phon_R01_S01_1      119.992       157.302        74.997         0.00784   
phon_R01_S01_2      122.400       148.650       113.819         0.00968   
phon_R01_S01_3      116.682       131.111       111.555         0.01050   
phon_R01_S01_4      116.676       137.871       111.366         0.00997   
phon_R01_S01_5      116.014       141.781       110.655         0.01284   
phon_R01_S01_6      120.552       131.162       113.787         0.00968   
phon_R01_S02_1      120.267       137.244       114.820         0.00333   
phon_R01_S02_2      107.332       113.840       104.315         0.00290   
phon_R01_S02_3       95.730       132.068        91.754         0.00551   
phon_R01_S02_4       95.056       120.103        91.226         0.00532   
phon_R01_S02_5       88.333       112.240        84.072         0.00505   
phon_R01_S02_6       91.904       115.871        86.292         0.00540   
phon_R01_S04_1      136.926       159.866       131.276         0.00293   
phon_R01_S04_2      139.173       179.139        76.556         0.00390   
phon_R01_S04_3      152.845       163.305        75.836         0.00294   
phon_R01_S04_4      142.167       217.455        83.159         0.00369   
phon_R01_S04_5      144.188       349.259        82.764         0.00544   
phon_R01_S04_6      168.778       232.181        75.603         0.00718   
phon_R01_S05_1      153.046       175.829        68.623         0.00742   
phon_R01_S05_2      156.405       189.398       142.822         0.00768   
phon_R01_S05_3      153.848       165.738        65.782         0.00840   
phon_R01_S05_4      153.880       172.860        78.128         0.00480   
phon_R01_S05_5      167.930       193.221        79.068         0.00442   
phon_R01_S05_6      173.917       192.735        86.180         0.00476   
phon_R01_S06_1      163.656       200.841        76.779         0.00742   
phon_R01_S06_2      104.400       206.002        77.968         0.00633   
phon_R01_S06_3      171.041       208.313        75.501         0.00455   
phon_R01_S06_4      146.845       208.701        81.737         0.00496   
phon_R01_S06_5      155.358       227.383        80.055         0.00310   
phon_R01_S06_6      162.568       198.346        77.630         0.00502   
...                     ...           ...           ...             ...   
phon_R01_S42_1      236.200       244.663       102.137         0.00277   
phon_R01_S42_2      237.323       243.709       229.256         0.00303   
phon_R01_S42_3      260.105       264.919       237.303         0.00339   
phon_R01_S42_4      197.569       217.627        90.794         0.00803   
phon_R01_S42_5      240.301       245.135       219.783         0.00517   
phon_R01_S42_6      244.990       272.210       239.170         0.00451   
phon_R01_S43_1      112.547       133.374       105.715         0.00355   
phon_R01_S43_2      110.739       113.597       100.139         0.00356   
phon_R01_S43_3      113.715       116.443        96.913         0.00349   
phon_R01_S43_4      117.004       144.466        99.923         0.00353   
phon_R01_S43_5      115.380       123.109       108.634         0.00332   
phon_R01_S43_6      116.388       129.038       108.970         0.00346   
phon_R01_S44_1      151.737       190.204       129.859         0.00314   
phon_R01_S44_2      148.790       158.359       138.990         0.00309   
phon_R01_S44_3      148.143       155.982       135.041         0.00392   
phon_R01_S44_4      150.440       163.441       144.736         0.00396   
phon_R01_S44_5      148.462       161.078       141.998         0.00397   
phon_R01_S44_6      149.818       163.417       144.786         0.00336   
phon_R01_S49_1      117.226       123.925       106.656         0.00417   
phon_R01_S49_2      116.848       217.552        99.503         0.00531   
phon_R01_S49_3      116.286       177.291

In [24]:
X.dtypes

MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
dtype: object

In [4]:
y = X[['status']]
X = X.drop('status', axis=1)
X

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
name                                                                      
phon_R01_S01_1      119.992       157.302        74.997         0.00784   
phon_R01_S01_2      122.400       148.650       113.819         0.00968   
phon_R01_S01_3      116.682       131.111       111.555         0.01050   
phon_R01_S01_4      116.676       137.871       111.366         0.00997   
phon_R01_S01_5      116.014       141.781       110.655         0.01284   
phon_R01_S01_6      120.552       131.162       113.787         0.00968   
phon_R01_S02_1      120.267       137.244       114.820         0.00333   
phon_R01_S02_2      107.332       113.840       104.315         0.00290   
phon_R01_S02_3       95.730       132.068        91.754         0.00551   
phon_R01_S02_4       95.056       120.103        91.226         0.00532   
phon_R01_S02_5       88.333       112.240        84.072         0.00505   
phon_R01_S02_6       91.904       115.871        86.292         0.00540   
phon_R01_S04_1      136.926       159.866       131.276         0.00293   
phon_R01_S04_2      139.173       179.139        76.556         0.00390   
phon_R01_S04_3      152.845       163.305        75.836         0.00294   
phon_R01_S04_4      142.167       217.455        83.159         0.00369   
phon_R01_S04_5      144.188       349.259        82.764         0.00544   
phon_R01_S04_6      168.778       232.181        75.603         0.00718   
phon_R01_S05_1      153.046       175.829        68.623         0.00742   
phon_R01_S05_2      156.405       189.398       142.822         0.00768   
phon_R01_S05_3      153.848       165.738        65.782         0.00840   
phon_R01_S05_4      153.880       172.860        78.128         0.00480   
phon_R01_S05_5      167.930       193.221        79.068         0.00442   
phon_R01_S05_6      173.917       192.735        86.180         0.00476   
phon_R01_S06_1      163.656       200.841        76.779         0.00742   
phon_R01_S06_2      104.400       206.002        77.968         0.00633   
phon_R01_S06_3      171.041       208.313        75.501         0.00455   
phon_R01_S06_4      146.845       208.701        81.737         0.00496   
phon_R01_S06_5      155.358       227.383        80.055         0.00310   
phon_R01_S06_6      162.568       198.346        77.630         0.00502   
...                     ...           ...           ...             ...   
phon_R01_S42_1      236.200       244.663       102.137         0.00277   
phon_R01_S42_2      237.323       243.709       229.256         0.00303   
phon_R01_S42_3      260.105       264.919       237.303         0.00339   
phon_R01_S42_4      197.569       217.627        90.794         0.00803   
phon_R01_S42_5      240.301       245.135       219.783         0.00517   
phon_R01_S42_6      244.990       272.210       239.170         0.00451   
phon_R01_S43_1      112.547       133.374       105.715         0.00355   
phon_R01_S43_2      110.739       113.597       100.139         0.00356   
phon_R01_S43_3      113.715       116.443        96.913         0.00349   
phon_R01_S43_4      117.004       144.466        99.923         0.00353   
phon_R01_S43_5      115.380       123.109       108.634         0.00332   
phon_R01_S43_6      116.388       129.038       108.970         0.00346   
phon_R01_S44_1      151.737       190.204       129.859         0.00314   
phon_R01_S44_2      148.790       158.359       138.990         0.00309   
phon_R01_S44_3      148.143       155.982       135.041         0.00392   
phon_R01_S44_4      150.440       163.441       144.736         0.00396   
phon_R01_S44_5      148.462       161.078       141.998         0.00397   
phon_R01_S44_6      149.818       163.417       144.786         0.00336   
phon_R01_S49_1      117.226       123.925       106.656         0.00417   
phon_R01_S49_2      116.848       217.552        99.503         0.00531   
phon_R01_S49_3      116.286       177.291

In [9]:
y

status
name                  
phon_R01_S01_1       1
phon_R01_S01_2       1
phon_R01_S01_3       1
phon_R01_S01_4       1
phon_R01_S01_5       1
phon_R01_S01_6       1
phon_R01_S02_1       1
phon_R01_S02_2       1
phon_R01_S02_3       1
phon_R01_S02_4       1
phon_R01_S02_5       1
phon_R01_S02_6       1
phon_R01_S04_1       1
phon_R01_S04_2       1
phon_R01_S04_3       1
phon_R01_S04_4       1
phon_R01_S04_5       1
phon_R01_S04_6       1
phon_R01_S05_1       1
phon_R01_S05_2       1
phon_R01_S05_3       1
phon_R01_S05_4       1
phon_R01_S05_5       1
phon_R01_S05_6       1
phon_R01_S06_1       1
phon_R01_S06_2       1
phon_R01_S06_3       1
phon_R01_S06_4       1
phon_R01_S06_5       1
phon_R01_S06_6       1
...                ...
phon_R01_S42_1       0
phon_R01_S42_2       0
phon_R01_S42_3       0
phon_R01_S42_4       0
phon_R01_S42_5       0
phon_R01_S42_6       0
phon_R01_S43_1       0
phon_R01_S43_2       0
phon_R01_S43_3       0
phon_R01_S43_4       0
phon_R01_S43_5       0
phon_R01_S43_6       0
phon_R01_S44_1       1
phon_R01_S44_2       1
phon_R01_S44_3       1
phon_R01_S44_4       1
phon_R01_S44_5       1
phon_R01_S44_6       1
phon_R01_S49_1       0
phon_R01_S49_2       0
phon_R01_S49_3       0
phon_R01_S49_4       0
phon_R01_S49_5       0
phon_R01_S49_6       0
phon_R01_S50_1       0
phon_R01_S50_2       0
phon_R01_S50_3       0
phon_R01_S50_4       0
phon_R01_S50_5       0
phon_R01_S50_6       0

[195 rows x 1 columns]

In [17]:
print( type(y['status']))
print(type(y))
yy = y['status'].reshape(-1,1)
print(type(yy))


<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [31]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train['status']) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
 score = svc.score(X_test,y_test['status'])

In [33]:
score

0.81355932203389836

In [45]:
from sklearn.grid_search import GridSearchCV
#   "kernel" : ['linear', 'poly', 'rbf', 'sigmoid'],
svc1 = SVC()
 
param_grid = { 
       
           "gamma" : [ 0.001,  0.002,  0.003,  0.004,  0.005,  0.006,  0.007,  0.008,
        0.009,  0.01 ,  0.011,  0.012,  0.013,  0.014,  0.015,  0.016,
        0.017,  0.018,  0.019,  0.02 ,  0.021,  0.022,  0.023,  0.024,
        0.025,  0.026,  0.027,  0.028,  0.029,  0.03 ,  0.031,  0.032,
        0.033,  0.034,  0.035,  0.036,  0.037,  0.038,  0.039,  0.04 ,
        0.041,  0.042,  0.043,  0.044,  0.045,  0.046,  0.047,  0.048,
        0.049,  0.05 ,  0.051,  0.052,  0.053,  0.054,  0.055,  0.056,
        0.057,  0.058,  0.059,  0.06 ,  0.061,  0.062,  0.063,  0.064,
        0.065,  0.066,  0.067,  0.068,  0.069,  0.07 ,  0.071,  0.072,
        0.073,  0.074,  0.075,  0.076,  0.077,  0.078,  0.079,  0.08 ,
        0.081,  0.082,  0.083,  0.084,  0.085,  0.086,  0.087,  0.088,
        0.089,  0.09 ,  0.091,  0.092,  0.093,  0.094,  0.095,  0.096,
        0.097,  0.098,  0.099] ,
           "C" : [ 0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,
        0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,
        1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,  1.8 ,
        1.85,  1.9 ,  1.95]
}
 
CV_svc = GridSearchCV(estimator=svc1, param_grid=param_grid, cv= 10)
CV_svc.fit(X_train,y_train['status'])
CV_svc.best_params_

{'C': 1.65, 'gamma': 0.004}

In [46]:
cvbestmodel = SVC(C=1.65,gamma=0.004)
cvbestmodel.fit(X_train,y_train['status'])
cvbestscore = cvbestmodel.score(X_test,y_test['status'])
print(cvbestscore)

0.881355932203


In [37]:
crange = np.arange(0.05,2,0.05)
gammarange = np.arange(0.001,0.1,0.001)

In [36]:
crange

array([ 0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,
        0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,
        1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,  1.8 ,
        1.85,  1.9 ,  1.95])

In [38]:
gammarange

array([ 0.001,  0.002,  0.003,  0.004,  0.005,  0.006,  0.007,  0.008,
        0.009,  0.01 ,  0.011,  0.012,  0.013,  0.014,  0.015,  0.016,
        0.017,  0.018,  0.019,  0.02 ,  0.021,  0.022,  0.023,  0.024,
        0.025,  0.026,  0.027,  0.028,  0.029,  0.03 ,  0.031,  0.032,
        0.033,  0.034,  0.035,  0.036,  0.037,  0.038,  0.039,  0.04 ,
        0.041,  0.042,  0.043,  0.044,  0.045,  0.046,  0.047,  0.048,
        0.049,  0.05 ,  0.051,  0.052,  0.053,  0.054,  0.055,  0.056,
        0.057,  0.058,  0.059,  0.06 ,  0.061,  0.062,  0.063,  0.064,
        0.065,  0.066,  0.067,  0.068,  0.069,  0.07 ,  0.071,  0.072,
        0.073,  0.074,  0.075,  0.076,  0.077,  0.078,  0.079,  0.08 ,
        0.081,  0.082,  0.083,  0.084,  0.085,  0.086,  0.087,  0.088,
        0.089,  0.09 ,  0.091,  0.092,  0.093,  0.094,  0.095,  0.096,
        0.097,  0.098,  0.099])

In [48]:
type(crange)

numpy.ndarray

In [50]:
bestscore = 0.0
best_c = 0
best_gamma = 0

for c in (crange):
    for g in (gammarange):
        model = SVC(C=c,gamma=g)
        model.fit(X_train,y_train['status'])
        score = model.score(X_test,y_test['status'])
        if score > bestscore:
            bestscore = score
            best_c = c
            best_gamma = g
    
print("bestscore is = ", bestscore)
print("best c is = ", best_c)
print("best gamma is = ", best_gamma)


bestscore is =  0.915254237288
best c is =  1.65
best gamma is =  0.005


In [59]:
from sklearn import preprocessing

def preprocessandScore(processor,xtrain,ytrain,xtest,ytest, Cs, gs):
    pm = processor.fit(xtrain)
    Xtrain = pm.transform(xtrain)
    Xtest = pm.transform(xtest)
    bestscore = 0.0
    best_c = 0
    best_gamma = 0

    for c in (Cs):
        for g in (gs):
            model = SVC(C=c,gamma=g)
            model.fit(Xtrain,y_train['status'])
            score = model.score(Xtest,y_test['status'])
            if score > bestscore:
                bestscore = score
                best_c = c
                best_gamma = g

    print('processor is ', type(processor))
    print("bestscore is = ", bestscore)
    print("best c is = ", best_c)
    print("best gamma is = ", best_gamma)


    return model

In [63]:


#T = preprocessing.StandardScaler().fit_transform(df)
#T = preprocessing.MinMaxScaler().fit_transform(df)
#T = preprocessing.MaxAbsScaler().fit_transform(df)
#T = preprocessing.Normalizer().fit_transform(df)
#T = preprocessing.KernelCenterer().fit

preprocessandScore(preprocessing.StandardScaler(),X_train,y_train,X_test,y_test,crange,gammarange)

processor is  <class 'sklearn.preprocessing.data.StandardScaler'>
bestscore is =  0.932203389831
best c is =  1.55
best gamma is =  0.097


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [64]:
preprocessandScore(preprocessing.Normalizer(),X_train,y_train,X_test,y_test,crange,gammarange)

processor is  <class 'sklearn.preprocessing.data.Normalizer'>
bestscore is =  0.796610169492
best c is =  0.05
best gamma is =  0.001


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [65]:
preprocessandScore(preprocessing.MinMaxScaler(),X_train,y_train,X_test,y_test,crange,gammarange)

processor is  <class 'sklearn.preprocessing.data.MinMaxScaler'>
bestscore is =  0.881355932203
best c is =  0.75
best gamma is =  0.097


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [66]:
preprocessandScore(preprocessing.KernelCenterer(),X_train,y_train,X_test,y_test,crange,gammarange)

processor is  <class 'sklearn.preprocessing.data.KernelCenterer'>
bestscore is =  0.915254237288
best c is =  1.7
best gamma is =  0.006


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [67]:
preprocessandScore(preprocessing.MaxAbsScaler(),X_train,y_train,X_test,y_test,crange,gammarange)

processor is  <class 'sklearn.preprocessing.data.MaxAbsScaler'>
bestscore is =  0.881355932203
best c is =  1.2
best gamma is =  0.098


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [70]:
pcarange = np.arange(4,15,1)
pcarange

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
from sklearn.decomposition import PCA

def preprocessAndScoreWithPCA(processor,xtrain,ytrain,xtest,ytest, Cs, gs, pcas):
    pm = processor.fit(xtrain)
    Xtrain = pm.transform(xtrain)
    Xtest = pm.transform(xtest)
    bestscore = 0.0
    best_c = 0
    best_gamma = 0
    best_components = 0
    
    for p in (pcas):
        pca = PCA(n_components=p, svd_solver='randomized', random_state=7)
        pca.fit(Xtrain)
        XTtrain = pca.transform(Xtrain)
        XTtest = pca.transform(Xtest)
        for c in (Cs):
            for g in (gs):
                model = SVC(C=c,gamma=g)
                model.fit(XTtrain,y_train['status'])
                score = model.score(XTtest,y_test['status'])
                if score > bestscore:
                    bestscore = score
                    best_c = c
                    best_gamma = g
                    best_components = p

    print('processor is ', type(processor))
    print("bestscore is = ", bestscore)
    print("best c is = ", best_c)
    print("best gamma is = ", best_gamma)
    print("best pca components are: ", best_components)


    return model

In [79]:
preprocessAndScoreWithPCA(preprocessing.StandardScaler(),X_train,y_train,X_test,y_test,crange,gammarange,pcarange)

processor is  <class 'sklearn.preprocessing.data.StandardScaler'>
bestscore is =  0.932203389831
best c is =  1.65
best gamma is =  0.098
best pca components are:  7


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [80]:
nneighbours = np.arange(2,6,1)
ncomponents = np.arange(4,7,1)

In [82]:
from sklearn import manifold


def preprocessAndScoreWithISOMAP(processor,xtrain,ytrain,xtest,ytest, Cs, gs, neighbours,components):
    pm = processor.fit(xtrain)
    Xtrain = pm.transform(xtrain)
    Xtest = pm.transform(xtest)
    bestscore = 0.0
    best_c = 0
    best_gamma = 0
   
    best_n_neighbours = 0
    best_n_components = 0
    
    for n in (neighbours):
        for cmp in (components):
            iso = manifold.Isomap(n, cmp)
            iso.fit(Xtrain)
            XTtrain = iso.transform(Xtrain)
            XTtest = iso.transform(Xtest)
            for c in (Cs):
                for g in (gs):
                    model = SVC(C=c,gamma=g)
                    model.fit(XTtrain,y_train['status'])
                    score = model.score(XTtest,y_test['status'])
                    if score > bestscore:
                        bestscore = score
                        best_c = c
                        best_gamma = g
                        best_n_neighbours = n
                        best_n_components = cmp

    print('processor is ', type(processor))
    print("bestscore is = ", bestscore)
    print("best c is = ", best_c)
    print("best gamma is = ", best_gamma)
    print("best iso components are: ", best_n_components)
    print("best iso neighbours are:",  best_n_neighbours)


    return model

In [84]:
preprocessAndScoreWithISOMAP(preprocessing.StandardScaler(),X_train,y_train,X_test,y_test,crange,gammarange,nneighbours,ncomponents)

processor is  <class 'sklearn.preprocessing.data.StandardScaler'>
bestscore is =  0.949152542373
best c is =  0.75
best gamma is =  0.05
best iso components are:  5
best iso neighbours are: 2


SVC(C=1.9500000000000002, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.099000000000000005,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [85]:
nneighbours

array([2, 3, 4, 5])

In [86]:
ncomponents

array([4, 5, 6])